/*
 * Copyright (c) 2026 @Natfii. All rights reserved.
 */

package com.zeroclaw.android.service

import com.zeroclaw.android.model.OnDeviceStatus
import com.zeroclaw.ffi.FfiException
import com.zeroclaw.ffi.SearchRepairHandler
import kotlinx.coroutines.runBlocking

/**
 * UniFFI callback handler that runs the metasearch self-repair prompt on
 * Gemini Nano via [OnDeviceInferenceBridge].
 *
 * Implements the [SearchRepairHandler] callback interface generated by
 * UniFFI. The Rust repair ladder invokes [complete] from a blocking-pool
 * thread (never the main thread), so blocking here is expected; the bridge
 * dispatches the actual inference to its own CPU/TPU dispatcher.
 *
 * Fails fast when the on-device model is not ready: availability is checked
 * first and a missing or still-downloading model raises
 * [FfiException.StateException] without triggering a model download. ML Kit
 * additionally blocks inference while the app is not the foreground
 * activity; that surfaces as a generation failure here and the Rust ladder
 * simply escalates to the configured provider rung — a failed attempt costs
 * one local call and nothing else.
 *
 * @param bridge On-device inference bridge; owned by this handler and
 *   released via [close].
 */
class SearchRepairNanoHandler(
    private val bridge: OnDeviceInferenceBridge = OnDeviceInferenceBridge(),
) : SearchRepairHandler {
    /**
     * Runs the repair prompt on the on-device model.
     *
     * @param prompt Repair prompt assembled by the Rust repair ladder.
     * @return The model's raw text answer (parsed and gated on the Rust side).
     * @throws FfiException.StateException when the model is unavailable or
     *   generation fails.
     */
    override fun complete(prompt: String): String =
        runBlocking {
            val status = bridge.checkModelStatus()
            if (status != OnDeviceStatus.Available) {
                throw FfiException.StateException(
                    "On-device model not ready: $status",
                )
            }
            bridge.generateText(prompt).getOrElse { error ->
                throw FfiException.StateException(
                    error.message ?: "On-device generation failed",
                )
            }
        }

    /**
     * Releases the underlying on-device model resources.
     *
     * Call after unregistering the handler at daemon shutdown; subsequent
     * [complete] calls would lazily re-initialize the model.
     */
    fun close() {
        bridge.close()
    }
}
