/*
 * Copyright (c) 2026 @Natfii. All rights reserved.
 */

package com.zeroclaw.android.data.saf

import android.content.Context
import android.net.Uri
import com.zeroclaw.ffi.FfiException
import com.zeroclaw.ffi.SharedFolderHandler
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * UniFFI callback handler that bridges Rust tool dispatch to SAF operations.
 *
 * Implements the [SharedFolderHandler] callback interface generated by UniFFI.
 * Parses tool parameters from JSON, delegates to [SharedFolderSafHelper],
 * and returns JSON result strings.
 *
 * @param context Android context for SAF access.
 * @param getFolderUri Lambda returning the current persisted SAF URI string.
 */
class SharedFolderCallbackHandler(
    private val context: Context,
    private val getFolderUri: () -> String,
) : SharedFolderHandler {
    private val helper = SharedFolderSafHelper(context)
    private val json = Json { ignoreUnknownKeys = true }

    override fun executeSharedFolderTool(
        toolName: String,
        paramsJson: String,
    ): String {
        val uriString = getFolderUri()
        if (uriString.isBlank()) {
            throw FfiException.StateException(
                "No shared folder configured. Pick a folder in Hub > Plugins > Shared Folder.",
            )
        }
        val rootUri = Uri.parse(uriString)

        return when (toolName) {
            "shared_folder_list" -> {
                val params = json.decodeFromString<ListParams>(paramsJson)
                helper.list(rootUri, params.path)
            }
            "shared_folder_read" -> {
                val params = json.decodeFromString<ReadParams>(paramsJson)
                helper.read(rootUri, params.path)
            }
            "shared_folder_write" -> {
                val params = json.decodeFromString<WriteParams>(paramsJson)
                helper.write(rootUri, params.path, params.content, params.isBase64, params.mkdir)
            }
            else -> throw FfiException.InvalidArgument("Unknown tool: $toolName")
        }
    }

    @Serializable
    private data class ListParams(
        val path: String = "/",
    )

    @Serializable
    private data class ReadParams(
        val path: String,
    )

    @Serializable
    private data class WriteParams(
        val path: String,
        val content: String? = null,
        val isBase64: Boolean = false,
        val mkdir: Boolean = false,
    )
}
