#!/usr/bin/env bash
# Copyright (c) 2026 @Natfii. All rights reserved.
#
# Cross-compile the bundled SSH client (zssh) for Android and stage it as
# libssh.so in jniLibs, so the in-app shell can invoke `ssh user@host`.
# Mirrors build-ghostty.sh: the jniLibs output is gitignored and is
# regenerated by running this script.
#
# Requires: Rust with the android targets, cargo-ndk, and the Android NDK.
#
# Usage:
#   ANDROID_NDK_HOME=<path-to-ndk> ./scripts/build-zssh.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE="$PROJECT_ROOT/zeroclaw-android"
JNILIBS="$PROJECT_ROOT/app/src/main/jniLibs"

if [ -z "${ANDROID_NDK_HOME:-}" ]; then
    echo "ERROR: ANDROID_NDK_HOME is not set (point it at your Android NDK)."
    exit 1
fi

cd "$WORKSPACE"

echo "=== Cross-compiling zssh (release) for arm64-v8a + x86_64 ==="
cargo ndk -t arm64-v8a -t x86_64 build --release -p zssh

mkdir -p "$JNILIBS/arm64-v8a" "$JNILIBS/x86_64"
# cargo-ndk leaves the binary at target/<triple>/release/zssh. Package it as
# lib*.so so AGP bundles it into the read-only, exec-allowed nativeLibraryDir
# (Android SDK 35 W^X forbids exec from app-writable storage).
cp target/aarch64-linux-android/release/zssh "$JNILIBS/arm64-v8a/libssh.so"
cp target/x86_64-linux-android/release/zssh  "$JNILIBS/x86_64/libssh.so"

echo "=== Done ==="
ls -lh "$JNILIBS/arm64-v8a/libssh.so" "$JNILIBS/x86_64/libssh.so"
